#pragma once

// This file is generated by the Aion transpiler.
// DO NOT MODIFY

#include <array>
#include <bit>
#include <cstdint>
#include <cstddef>
namespace aion::runtime
{
    struct alignas(32) Event
    {
        int x;
    } ;
    inline bool _evaluate_predicate_x_(const Event& event)
    {
        return (true);
    } 
} ;
