/* emitter.cpp
 * Implementation of emitter.cppm
 */

module aion.codegen;

import std;
import aion.frontend;

namespace  aion::codegen
{
    void CEmitter::emit_line(std::string_view line)
    {
        out += std::string(indent_level * 4, ' ')
                + std::string(line) + "\n";
    }
    void  CEmitter::indent()
    {
        indent_level++;
    }
    void  CEmitter::dedent()
    {
        indent_level--;
    }
    void  CEmitter::emit_block_start(std::string_view line)
    {
        emit_line(line);
        emit_line("{");
        indent();
    }
    void  CEmitter::emit_block_end(std::string_view suffix)
    {
        dedent();
        emit_line(std::format("}} {}", suffix));
    }
    void  CEmitter::dump(const std::string_view filename) const
    {
        std::ofstream outfile;
        outfile.open(filename);
        outfile << out;
        outfile.close();
    }


    void emit_headers(CEmitter& emitter)
    {
        emitter.emit_line("#pragma once\n");
        // Any common headers like immintrin, string.h or others.
        emitter.emit_line("// This file is generated by the Aion transpiler.\n"
                          "// DO NOT MODIFY\n");

        emitter.emit_line("#include <array>");
        emitter.emit_line("#include <bit>");
        emitter.emit_line("#include <cstdint>");
        emitter.emit_line("#include <cstddef>");

        emitter.emit_block_start("namespace aion::runtime");
    }

    void emit_footers(CEmitter& emitter)
    {
        emitter.emit_block_end(";");
    }
};
