/* emitter.cpp
 * Implementation of emitter.cppm
 */

module aion.codegen;

import std;
import aion.frontend;

namespace  aion::codegen
{
    void CEmitter::emit_line(std::string_view line)
    {
        out += std::string(indent_level * 4, ' ')
                + std::string(line) + "\n";
    }
    void  CEmitter::indent()
    {
        indent_level++;
    }
    void  CEmitter::dedent()
    {
        indent_level--;
    }
    void  CEmitter::emit_block_start(std::string_view line)
    {
        emit_line(line);
        emit_line("{");
        indent();
    }
    void  CEmitter::emit_block_end(std::string_view suffix)
    {
        dedent();
        emit_line(std::format("}} {}", suffix));
    }
    void  CEmitter::dump(const std::string_view filename) const
    {
        std::ofstream outfile;
        outfile.open(filename);
        outfile << out;
        outfile.close();
    }


    void emit_headers(CEmitter& emitter)
    {
        emitter.emit_line("#pragma once\n");
        // Any common headers like immintrin, string.h or others.

        emitter.emit_line("// This file is generated by the Aion transpiler.\n"
                          "// DO NOT MODIFY\n");

        emitter.emit_line("// concepts.hpp starts");
        static const unsigned char concepts_raw[] = {
#embed "../../runtime/concepts.hpp"
        };
        emitter.emit_line(std::string_view(reinterpret_cast<const char*>(concepts_raw), sizeof(concepts_raw)));
        emitter.emit_line("// concepts.hpp ends\n\n");

        emitter.emit_line("// bitsets.hpp starts");
        static const unsigned char bitsets_raw[] = {
#embed "../../runtime/bitsets.hpp"
        };
        emitter.emit_line(std::string_view(reinterpret_cast<const char*>(bitsets_raw), sizeof(bitsets_raw)));
        emitter.emit_line("// bitsets.hpp ends\n\n");

        emitter.emit_line("// engine.hpp starts");
        static const unsigned char engine_raw[] = {
#embed "../../runtime/engine.hpp"
        };
        emitter.emit_line(std::string_view(reinterpret_cast<const char*>(engine_raw), sizeof(engine_raw)));
        emitter.emit_line("// engine.hpp ends\n\n");

        emitter.emit_block_start("namespace aion::runtime");
    }

    void emit_footers(CEmitter& emitter)
    {
        emitter.emit_block_end(";");
    }
};